## Arrays

Este tipo de datos, a diferencia de los anteriores, necesitan del módulo **numpy** para crearlos. Estas estructuras son similares a las listas pero con la diferencia que necesitaremos el método **array** del módulo **numpy**. La sintaxis para crear un *array* es de la siguiente forma

**numpy.array([dato1,datos,2,etc])**

A groso modo comparte las mismas características que una lista pero veremos que hay algorítmos y métodos que sólo aceptan datos tipo *array* y no *list*.

Veremos ejemplos más adelante, para ello importaremos primero la librería correspondiente bajo el apodo **np**

In [4]:
!pip install numpy # Descargar el módulo en caso de no tenerlo

In [1]:
import numpy as np

Creemos un array de tamaño $1x3$

In [2]:
a1 = np.array([1,2,3])
print("Nuestro array es " + str(a1) + " y su tipo: " + str(type(a1)))

Nuestro array es [1 2 3] y su tipo: <class 'numpy.ndarray'>


Como se aprecia, es un tipo de dato diferente. 

A diferencia de las listas, los *arrays* no pueden contener entradas de distintos tipos de datos, si se le instroducen distintos datos, dependiendo del caso, los convertirá a todos a cierto tipo de dato

In [10]:
a2 = np.array([1,True])
print("Nuestro array es " + str(a2) + " y sus tipos: " + str(type(a2[0])) + str(type(a2[1])))
a3 = np.array([1,"True"])
print("Nuestro array es " + str(a3) + " y sus tipos: " + str(type(a3[0])) + str(type(a3[1])))
a4 = np.array([1,2.3])
print("Nuestro array es " + str(a4) + " y sus tipos: " + str(type(a4[0])) + str(type(a4[1])))

Nuestro array es [1 1] y sus tipos: <class 'numpy.int32'><class 'numpy.int32'>
Nuestro array es ['1' 'True'] y sus tipos: <class 'numpy.str_'><class 'numpy.str_'>
Nuestro array es [1.  2.3] y sus tipos: <class 'numpy.float64'><class 'numpy.float64'>


Podemos accesar a su elementos de la manera que ya conocemos

In [55]:
print(a2[0])
print(a3[0])
print(a3[1])
print(a4[1])

1
1
True
2.3


### Vectores

Ahora para crear vectores renglones y columnas tenemos que seguir la siguiente sintaxis, resp:

- **Renglón**

In [12]:
vec_ren_1 = np.array([[1,2,3]])
print(vec_ren_1)

[[1 2 3]]


Existe una alternativa usando el método **reshape(n,m)** donde **n** es el número de renglones y **m** el número de columnas de las dimensiones de la matriz en la que acomodaremos el vector

In [15]:
aux_1 = np.array([1,2,3])
vec_ren_2 = aux_1.reshape(1,3)
print(vec_ren_2)

[[1 2 3]]


- **Columna**

In [16]:
vec_col_1 = np.array([[1],
                     [2],
                     [3]])
print(vec_col_1)

[[1]
 [2]
 [3]]


In [17]:
aux_2 = np.array([1,2,3])
vec_col_2 = aux_2.reshape(3,1)
print(vec_col_2)

[[1]
 [2]
 [3]]


Si deseamos obtener la dimensión del vector, tenemos el método **shape()**

In [19]:
print("dim. de vec_ren_1 = " + str(vec_ren_1.shape))
print("dim. de vec_col_2 = " + str(vec_col_2.shape))

dim. de vec_ren_1 = (1, 3)
dim. de vec_col_2 = (3, 1)


Para ver el tipo de elemento almacenado está **dtype**

In [20]:
print("Datos almacenados en vec_col_2: " + str(vec_col_2.dtype))

Datos almacenados en vec_col_2: int32


Usaremos el método **T** para transponer el segundo vector columna

In [45]:
vec_col_2.T

array([[1, 2, 3]])

### Operaciones Vectoriales

- **Producto escalar**

Tomemos al escalar $a=2.5$ y a los vectores *vec_ren_1* y *vec_ren_2*

In [33]:
a = 2.5
pe_1 = a*vec_ren_1
print(pe_1)
print("")
pe_2 = a*vec_col_2
print(pe_2)

[[2.5 5.  7.5]]

[[2.5]
 [5. ]
 [7.5]]


- **Sumar o resar vectores**

Declararemos otros vectores para esto

In [37]:
vec_ren_3 = np.array([[5.3,5,1.5]])
print(vec_ren_3)

[[5.3 5.  1.5]]


**Suma:**

In [38]:
sum_vec = vec_ren_2 + vec_ren_3
print(sum_vec)

[[6.3 7.  4.5]]


**Resta:**

In [41]:
res_vec = vec_ren_3 - vec_ren_2
print(res_vec)

[[ 4.3  3.  -1.5]]


- **Prodcuto punto:**

Usaremos el método **T** para transponer el segundo vector renglón para este producto punto o producto escalar canónico de $R^{3}$

In [49]:
vec_ren_2.dot(vec_ren_2.T) # Norma

array([[14]])

In [50]:
vec_ren_2.dot(vec_ren_3.T)

array([[19.8]])

In [51]:
vec_ren_2.dot(vec_col_2)

array([[14]])

- **Prodcuto matricial:**

In [53]:
vec_ren_2@vec_col_2

array([[14]])

In [54]:

vec_col_2@vec_ren_2

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

### Matrices

Para crear matrices es análogo a los vectores e incluso intruitivo

In [59]:
Mat_1 = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7,8,9]])
print(Mat_1)
print("Dimensión = " + str(Mat_1.shape))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Dimensión = (3, 3)


Accedamos a sus distintas entradas

In [27]:
print("M(1,1) = " + str(Mat_1[0][0])
     + "\nM(2,3) = " + str(Mat_1[1][2]))

M(1,1) = 1
M(2,3) = 6


In [60]:
print('Columna 1:', Mat_1[:,0])
print('Columna 2:', Mat_1[:,1])
print('Renglón 1:', Mat_1[0,:])

Columna 1: [1 4 7]
Columna 2: [2 5 8]
Renglón 1: [1 2 3]


### Operaciones matriciales

- **Producto escalar:**

In [56]:
b = 2.5
Mat_2 = np.array([[3,6,7],
                 [12,0,4],
                 [0,1,0]])

In [57]:
b*Mat_2

array([[ 7.5, 15. , 17.5],
       [30. ,  0. , 10. ],
       [ 0. ,  2.5,  0. ]])

- **Suma y resta**

In [61]:
Mat_1 + Mat_2

array([[ 4,  8, 10],
       [16,  5, 10],
       [ 7,  9,  9]])

In [62]:
Mat_1 - Mat_2

array([[-2, -4, -4],
       [-8,  5,  2],
       [ 7,  7,  9]])

- **Producto matricial:**

In [64]:
Mat_1@Mat_2

array([[ 27,   9,  15],
       [ 72,  30,  48],
       [117,  51,  81]])

In [65]:
Mat_2@Mat_1

array([[ 76,  92, 108],
       [ 40,  56,  72],
       [  4,   5,   6]])

- **Producto Matriz vector**

Con un vector renglón, se toma este y se mutiplica entrada por entrada a cada renglón de la matriz y de manera intuitiva, con un vector columna, este vector se multiplciará cada entrada por columna de la matriz. Para ejemplificar esto, veamos los siguientes ejemplos

In [67]:
Mat_1*vec_ren_2

array([[ 1,  4,  9],
       [ 4, 10, 18],
       [ 7, 16, 27]])

In [68]:
Mat_1*vec_col_2

array([[ 1,  2,  3],
       [ 8, 10, 12],
       [21, 24, 27]])